ResumeBuilder/Models/DomainModels/ResumeTemplate.cs
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;
using Microsoft.AspNetCore.Mvc.ModelBinding.Validation;


namespace ResumeBuilder.Models.DomainModels
{
    public class ResumeTemplate 
    {
        public Guid Id { get; set; }
        public string TemplateName { get; set; }
        public string TemplateDescription { get; set; }
        public DateTime CreatedDate { get; set; } = DateTime.Now;
        public bool IsActive { get; set; }
        public bool IsDeleted { get; set; }
    }
}

ResumeBuilder/Areas/Admin/Controllers/ResumeTemplatesController.cs
using System;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Identity;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Hosting;
using ResumeBuilder.Models.DomainModels;
using Microsoft.AspNetCore.Authorization;
using ResumeBuilder.Models.Repository.IRepository;



namespace ResumeBuilder.Controllers
{
    [Area("Admin")]
    [Authorize(Roles = "Admin,User")]
    public class ResumeTemplatesController : Controller
    {
        private readonly IUnitOfWork _unitOfWork;
        private readonly IWebHostEnvironment _hostEnvironment;
        private readonly SignInManager<IdentityUser> _signInManager;
        private readonly UserManager<IdentityUser> _userManager;
        private readonly RoleManager<IdentityRole> _roleManager;

        public ResumeTemplatesController(
            UserManager<IdentityUser> userManager,
            SignInManager<IdentityUser> signInManager,
            IUnitOfWork unitOfWork,
            RoleManager<IdentityRole> roleManager,
            IWebHostEnvironment hostEnvironment)
        {
            _roleManager = roleManager;
            _userManager = userManager;
            _signInManager = signInManager;
            _unitOfWork = unitOfWork;
            _hostEnvironment = hostEnvironment;
        }
        public IActionResult Index()
        {
            return View();
        }

        [HttpGet]
        public IActionResult Upsert(Guid? id)
        {
            var resumeTemplate = new ResumeTemplate();
            if (id == null)
            {
                // create new project
                return View(resumeTemplate);
            }
            resumeTemplate = _unitOfWork.ResumeTemplateRepository
                .GetFirstOrDefault(u => u.Id == id);
            return View(resumeTemplate);

        }

        [HttpPost]
        public async Task<IActionResult> Upsert(ResumeTemplate obj)
        {
            if (ModelState.IsValid)
            {
                if (obj.Id == null || obj.Id == Guid.Empty)
                {
                    _unitOfWork.ResumeTemplateRepository.Add(obj);
                    TempData["success"] = "Template created Successfully";
                }
                else
                {
                    _unitOfWork.ResumeTemplateRepository.Update(obj);
                    TempData["success"] = "Template updated Successfully";
                }
                _unitOfWork.Save();

                var user = await _userManager.GetUserAsync(User);
                // get the user manager from the owin context
                // get user roles
                var roles = await _userManager.GetRolesAsync(user);
                if (roles.Contains("Admin"))
                    return RedirectToAction("Index");
                return RedirectToAction("Index", "Home", new { area = "Customer" });

            }
            return View(obj);

        }
        [HttpGet]
        public async Task<IActionResult> ViewResume()
        {
            return View();
        }
        [HttpGet]
        public async Task<IActionResult> ViewContactUs()
        {
            return View();
        }
        [HttpGet]
        public async Task<IActionResult> AdminManagement()
        {
            return View();
        }
        #region API CALLS
        [HttpGet]
        public IActionResult GetAll()
        {
            var projList = _unitOfWork.ResumeTemplateRepository
                .GetAll()
                .Where(x => x.IsDeleted == false);
            return Json(new { data = projList });
        }
        [HttpGet]
        public IActionResult GetAllContactFeedBack()
        {
            var contactList = _unitOfWork.ContactUsRepository
                .GetAll();
            return Json(new { data = contactList });
        }
        [HttpDelete]
        public IActionResult Delete(Guid? id)
        {
            var obj = _unitOfWork.ResumeTemplateRepository.GetFirstOrDefault(u => u.Id == id);
            if (obj == null)
                return Json(new { success = false, message = "Error while deleting" });

            obj.IsDeleted = true;

            _unitOfWork.ResumeTemplateRepository.Update(obj);
            _unitOfWork.Save();
            return Json(new { success = true, message = "Delete successful" });

        }
        #endregion
    }

}

ResumeBuilder/Areas/Admin/Views/ResumeTemplates/AdminManagement.cshtml
@{
    ViewData["Title"] = "AdminManagement";
}


<div class="row" style="margin-top:15px;" >
    <div class="col-md-2"></div>
    <div class="col-md-3">
        <div class="thumbnail">
            <a class="dropdown-item" asp-area="Admin" asp-controller="User" asp-action="Index">
                <img src="/images/admin/adminimage01.png" class="img-circle" alt="Fjords" style="width:100%">
                <div class="caption">
                    <p>User Accounts</p>
                </div>
            </a>
        </div>
    </div>

    <div class="col-md-2"></div>

    <div class="col-md-3">
        <div class="thumbnail">
            <a class="dropdown-item " asp-area="Admin" asp-controller="ResumeTemplates" asp-action="Index">
                <img src="/images/admin/adminimage02.png" alt="Lights" class="img-circle" style="width:100%">
                <div class="caption">
                <p>Resume Templates</p>
                </div>
            </a>
        </div>
    </div>
    <div class="col-md-2"></div>
    <br />
    <div class="col-md-2"></div>
    <div class="col-md-3">
        <div class="thumbnail">
            <a class="dropdown-item " asp-area="Admin" asp-controller="ResumeTemplates" asp-action="ViewResume">
                <img src="/images/admin/adminimage03.png" alt="Lights" class="img-circle" style="width:100%">
                <div class="caption">
                    <p>View Resume</p>
                </div>
            </a>
        </div>
    </div>
    <div class="col-md-2"></div>
    <div class="col-md-3">
        <div class="thumbnail">
            <a class="dropdown-item " asp-area="Admin" asp-controller="ResumeTemplates" asp-action="ViewContactUs">
                <img src="/images/admin/adminimage04.png" class="img-circle" alt="Lights" style="width:100%">
                <div class="caption">
                    <p>View FeedBack</p>
                </div>
            </a>
        </div>
    </div>
    <div class="col-md-2"></div>
</div>

ResumeBuilder/Areas/Admin/Views/ResumeTemplates/Index.cshtml
@{
    ViewData["Title"] = "Index";
}

<partial name="_Notification" />


<div class="container" p-3>
    <div class="row pt-4">
        <div class="col-6">
            <h2 class="text-primary">Resume Templates</h2>
        </div>
        <div class="col-6 text-end">
            <a asp-controller="ResumeTemplates" asp-action="Upsert" class="btn btn-primary">
                <i class="bi bi-plus-circle"></i>
                &nbsp;Add New Resume Template</a>
        </div>
        <br /><br />

    </div>


    <div class="overflow-auto">
        <table id="ResumeTemplateTable" class="table table-bordered table-striped" style="width:100%">
            <thead>
                <tr>
                    <th> Template Name </th>
                    <th> Template Description</th>
                    <th> Created Date</th>
                    <th> Action </th>
                </tr>
            </thead>
        </table>
    </div>

</div>
    @section Scripts{
    <script src="~/js/ResumeTemplate.js"></script>
    }

ResumeBuilder/Areas/Admin/Views/ResumeTemplates/Upsert.cshtml
@using Microsoft.AspNetCore.Identity
@inject SignInManager<IdentityUser> SignInManager
@inject UserManager<IdentityUser> UserManager
@model ResumeBuilder.Models.DomainModels.ResumeTemplate
@{
    var user = await SignInManager.UserManager.GetUserAsync(User);
    // Get the roles for the user
    var roles = await SignInManager.UserManager.GetRolesAsync(user);
}
<form method="post" asp-action="Upsert" enctype="multipart/form-data">
    <input asp-for="Id" hidden />
    <div class="row">
        <div class="col-10">
            <div class="border p-3 mt-4 row">
                <div class="col-12 pb-2">
                    <h2 class="text-primary">@(Model.Id != new Guid("00000000-0000-0000-0000-000000000000") ? "Update" : "Create New") Resume Template</h2>
                    <hr />
                </div>
                <div class="mb-3">
                    <label asp-for="TemplateName">Template Name:</label>
                    <input asp-for="TemplateName" class="form-control" />
                    <span asp-validation-for="TemplateName" class="text-danger"></span>
                </div>
                <div class="mb-3">
                    <label asp-for="TemplateDescription">Template Description:</label>
                    <input asp-for="TemplateDescription" class="form-control" />
                    <span asp-validation-for="TemplateDescription" class="text-danger"></span>
                </div>
                <div class="mb-3">
                    <label asp-for="IsActive">Active:</label>
                    @Html.CheckBoxFor(m => m.IsActive )
                    <span asp-validation-for="IsActive" class="text-danger"></span>
                </div>
                <div class="mb-3 col-12">
                    @if (Model.Id != new Guid("00000000-0000-0000-0000-000000000000"))
                    {
                        <button type="submit" class="btn btn-primary" style="width:150px">Update</button>

                    }
                    else
                    {
                        <button type="submit" onclick="return ValidateInput()" class="btn btn-primary" style="width:150px">Add</button>

                    }
                    <a asp-controller="ResumeTemplates" asp-action="Index" class="btn btn-secondary" style="width:150px">
                        Back to List
                    </a>
                </div>
            </div>
        </div>
    </div>



</form>

@section Scripts{
    @{
        <partial name="_ValidationScriptsPartial" />
    }
}

ResumeBuilder/Areas/Admin/Views/ResumeTemplates/ViewContactUs.cshtml
@{
    ViewData["Title"] = "Contact Us";
}
<partial name="_Notification" />
<div class="container" p-3>
    <div class="row pt-4">
        <div class="col-6">
            <h2 class="text-primary">User Feed Back through Contact Us</h2>
        </div>
        <br /><br />
    </div>
    <div class="overflow-auto">
        <table id="ContactUs" class="table table-bordered table-striped" style="width:100%">
            <thead>
                <tr>
                    <th> First Name </th>
                    <th> Last Name </th>
                    <th> Email </th>
                    <th> Message</th>
                    <th> Detail</th>
                </tr>
            </thead>
        </table>
    </div>

</div>
@section Scripts{
    <script src="~/js/ContactUs.js"></script>
}

ResumeBuilder/Areas/Admin/Views/ResumeTemplates/ViewResume.cshtml
@{
    ViewData["Title"] = "My Resume";
}
<partial name="_Notification" />
<div class="container" p-3>
    <div class="row pt-4">
        <div class="col-6">
            <h2 class="text-primary">Resumes</h2>
        </div>
        <br /><br />
    </div>
    <div class="overflow-auto">
        <table id="Resume" class="table table-bordered table-striped" style="width:100%">
            <thead>
                <tr>
                    <th> First Name </th>
                    <th> Last Name </th>
                    <th> Phone</th>
                    <th> Email </th>
                    <th> Action </th>
                </tr>
            </thead>
        </table>
    </div>

</div>
@section Scripts{
    <script src="~/js/MyResume.js"></script>
}